steps:
- name: node:16
  entrypoint: npm
  dir: ./Client
  args: ['install']
#- name: node
#  entrypoint: npm
#  dir : ./Client
#  args: ['start']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "client.yaml"]
  dir: ./Client
options:
 logging: CLOUD_LOGGING_ONLY